theme: jekyll-theme-hacker
title: techfreak.ch Blog
description: Some stuff for me to remember
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-mentions